Make PTERO_DEPLOY_APP_NAME env variable a thing
The reason for this is that we'd like to reduce the duplication between
staging and production supervisord configuration files.  When we
describe the command supervisor is supposed to run, it would be nice to
not have to specify the name of the app on the command-line.

diff --git a/libexec/workers-common b/libexec/workers-common
--- a/libexec/workers-common
+++ b/libexec/workers-common
@@ -1,8 +1,7 @@
 trap 'kill -TERM $PID; wait $PID' TERM INT
 
-USAGE="Usage: $0 DEPLOYMENT_CONFIG APP_NAME"
+USAGE="Usage: $0 DEPLOYMENT_CONFIG"
 DEPLOYMENT_CONFIG=${1?"$USAGE"}
-APP_NAME=${2?"$USAGE"}
 
 source $PTERO_COMMON
 
@@ -13,16 +12,21 @@ fi
 
 CONFIG_FILE=$(python_realpath $DEPLOYMENT_CONFIG)
 
-log "Setting up environment for $APP_NAME worker from config file: $CONFIG_FILE"
-
-verify_jq
-if [ $(jq '.services?.'"\"${APP_NAME}\""'|type|@text' ${CONFIG_FILE}) = '"null"' ]; then
-    echo "Failed to find configuration for service ${APP_NAME} in config file ${CONFIG_FILE}" 1>&2
+if [[ -z "$PTERO_DEPLOY_APP_NAME" ]]; then
+    echo "You must export PTERO_DEPLOY_APP_NAME"
     exit 1
 fi
 
-VARS=$(jq -r '.services.'"\"${APP_NAME}\""'.environment|with_entries(.key = .key + "=" + .value)|keys|@sh' "${CONFIG_FILE}" | sed s/\'//g)
-WORKER_VARS=$(jq -r '.services.'"\"${APP_NAME}\""'."worker-environment"|with_entries(.key = .key + "=" + .value)|keys|@sh' "${CONFIG_FILE}" | sed s/\'//g)
+log "Setting up environment for $PTERO_DEPLOY_APP_NAME worker from config file: $CONFIG_FILE"
+
+verify_jq
+if [ $(jq '.services?.'"\"${PTERO_DEPLOY_APP_NAME}\""'|type|@text' ${CONFIG_FILE}) = '"null"' ]; then
+    echo "Failed to find configuration for service ${PTERO_DEPLOY_APP_NAME} in config file ${CONFIG_FILE}" 1>&2
+    exit 1
+fi
+
+VARS=$(jq -r '.services.'"\"${PTERO_DEPLOY_APP_NAME}\""'.environment|with_entries(.key = .key + "=" + .value)|keys|@sh' "${CONFIG_FILE}" | sed s/\'//g)
+WORKER_VARS=$(jq -r '.services.'"\"${PTERO_DEPLOY_APP_NAME}\""'."worker-environment"|with_entries(.key = .key + "=" + .value)|keys|@sh' "${CONFIG_FILE}" | sed s/\'//g)
 
 for env_var in "$VARS $WORKER_VARS"; do
     eval "export $env_var"
